sonar.projectKey=erik-marten_VeriLog
sonar.organization=erik-marten
sonar.host.url=https://sonarcloud.io

# JaCoCo reports for modules with tests
sonar.coverage.jacoco.xmlReportPaths=VeriLogJava/verilog-core/build/reports/jacoco/test/jacocoTestReport.xml,VeriLogJava/verilog-cli/build/reports/jacoco/test/jacocoTestReport.xml

# additional paths
sonar.java.binaries=VeriLogJava/verilog-core/build/classes/java/main,VeriLogJava/verilog-cli/build/classes/java/main
sonar.sources=VeriLogJava/verilog-core/src/main,VeriLogJava/verilog-cli/src/main
sonar.tests=VeriLogJava/verilog-core/src/test,VeriLogJava/verilog-cli/src/test
