sonar.projectKey=erik-marten_VeriLog
sonar.organization=erik-marten
sonar.host.url=https://sonarcloud.io

# JaCoCo in subprojekt
sonar.coverage.jacoco.xmlReportPaths=VeriLogJava/build/reports/jacoco/test/jacocoTestReport.xml

# additional paths
sonar.sources=VeriLogJava/src/main
sonar.tests=VeriLogJava/src/test
